server:
  port: 8097
spring:
  application:
    name: auth-server
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:123@127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
cnct:
  jwt:
    secret: cnct@Login(Auth}*^31)&heihei% # 登录校验的密钥
    pubKeyPath: E:/secretkey/rsa1.pub # 公钥地址
    priKeyPath: E:/secretkey/rsa1.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: CNCT_TOKEN

